### ISSUE TITLE
Creating a basic view component for TCPDF

### ISSUE THREAD

**Issue by timpackwood1987** [vdespa/TCPDF-Joomla-Library#3]
Hi vdespa

Thanks for the library extension, I've used it before but out of Joomla. I've not got a lot of experience with creating Joomla components. Could you give me a bit of advice on how to call the library and create the view to generate a basic PDF?

appreciate your time

Tim

**Comment by vdespa** [comment]
Hi Tim,

to be very briefly, my general advice is to just use the given MVC structure from Joomla.

The Controller and the Model should be straightforward and the view should be a special PDF view (view.pdf.php) and a template (default.php) where you actually put the TCPDF specific code. 

If you need / want to do it in a pragmatic way (quick and dirty), you can just use the controller but I would not really recommend it. 

I recommend asking such questions on the Joomla Stackexchange: http://joomla.stackexchange.com/

If this is not clear enough for you let me know, I will try to improve the documentation.
